const PHONETICS = {
  "abnormal": "/æbnˈɔrmʌl/",
  "absence": "/ˈæbsʌns/",
  "academic": "/ˌækʌˈdɛmɪk/",
  "academy": "/ʌkˈædʌmi/",
  "accompany": "/ʌkˈʌmpʌni/",
  "accurate": "/ˈækjɝʌt/",
  "acknowledge": "/æknˈɑlɪdʒ/",
  "adjust": "/ʌdʒˈʌst/",
  "adopt": "/ʌdˈɑpt/",
  "adorable": "/ʌdˈɔrʌbʌl/",
  "advocate": "/ˈædvʌkʌt/",
  "ahead": "/ʌhˈɛd/",
  "air conditioner": "/ˈɛr kʌndˈɪʃʌnɝ/",
  "albania": "/ælbˈeɪniʌ/",
  "albert einstein": "/ˈælbɝt ˈaɪnstaɪn/",
  "alexander fleming": "/ˌælʌɡˈzændɝ flˈɛmɪŋ/",
  "alleviate": "/ʌlˈiviˌeɪt/",
  "alternative": "/ɔltˈɝnʌtɪv/",
  "amuse": "/ʌmjˈuz/",
  "amusement": "/ʌmjˈuzmʌnt/",
  "anger": "/ˈæŋɡɝ/",
  "anxiety": "/æŋzˈaɪʌti/",
  "apparently": "/ʌpˈɛrʌntli/",
  "appeal": "/ʌpˈil/",
  "appeal to": "/ʌpˈil tˈu/",
  "appetite": "/ˈæpʌtˌaɪt/",
  "appliance": "/ʌplˈaɪʌns/",
  "appropriate": "/ʌprˈoʊpriʌt/",
  "approve": "/ʌprˈuv/",
  "aquarium": "/ʌkwˈɛriʌm/",
  "artificial": "/ˌɑrtʌˈfɪʃʌl/",
  "artificial intelligence (ai)": "/ˌɑrtʌˈfɪʃʌl ˌɪnˈtɛlʌdʒʌns/",
  "ashamed": "/ʌʃˈeɪmd/",
  "aspect": "/ˈæspˌɛkt/",
  "assess": "/ʌsˈɛs/",
  "assessment": "/ʌsˈɛsmʌnt/",
  "assumption": "/ʌsˈʌmpʃʌn/",
  "at work": "/ˈæt wˈɝk/",
  "attain": "/ʌtˈeɪn/",
  "automatic": "/ˌɔtʌˈmætɪk/",
  "available": "/ʌvˈeɪlʌbʌl/",
  "bacterium": "/bæktˈɪriʌm/",
  "ban": "/bˈæn/",
  "barely": "/bˈɛrli/",
  "barrier": "/bˈæriɝ/",
  "batch": "/bˈætʃ/",
  "be comprised of": "/bˈi kʌmprˈaɪzd ˈʌv/",
  "bend": "/bˈɛnd/",
  "bless": "/blˈɛs/",
  "boil": "/bˈɔɪl/",
  "bomb": "/bˈɑm/",
  "boost": "/bˈust/",
  "botanical": "/bʌtˈænɪkʌl/",
  "bother": "/bˈɑðɝ/",
  "boundary": "/bˈaʊndɝi/",
  "bow": "/bˈaʊ/",
  "brazil": "/brʌzˈɪl/",
  "break down": "/brˈeɪk dˈaʊn/",
  "broom": "/brˈum/",
  "buffet": "/bˈʌfʌt/",
  "bulgaria": "/bʌlɡˈɛriʌ/",
  "bush": "/bˈʊʃ/",
  "by comparison": "/bˈaɪ kʌmpˈɛrʌsʌn/",
  "by contrast": "/bˈaɪ kˈɑntræst/",
  "call on": "/kˈɔl ˈɑn/",
  "cancer": "/kˈænsɝ/",
  "career": "/kɝˈɪr/",
  "catch fire": "/kˈætʃ fˈaɪɝ/",
  "cease": "/sˈis/",
  "ceiling": "/sˈilɪŋ/",
  "celebrity": "/sʌlˈɛbrɪti/",
  "characteristic": "/kˌɛrʌktˈɝɪstɪk/",
  "chart": "/tʃˈɑrt/",
  "cheek": "/tʃˈik/",
  "chemical": "/kˈɛmʌkʌl/",
  "chest": "/tʃˈɛst/",
  "chin": "/tʃˈɪn/",
  "christian": "/krˈɪstʃʌn/",
  "circumstance": "/sˈɝkʌmstˌæns/",
  "clarify": "/klˈɛrʌfˌaɪ/",
  "clone": "/klˈoʊn/",
  "cloth": "/klˈɔθ/",
  "column": "/kˈɑlʌm/",
  "combine": "/kˈɑmbaɪn/",
  "come to power": "/kˈʌm tˈu pˈaʊɝ/",
  "command": "/kʌmˈænd/",
  "commit": "/kʌmˈɪt/",
  "commit oneself to (sth/doing sth/do sth)": "/kʌmˈɪt wˌʌnˈsɛlf tˈu/",
  "committed": "/kʌmˈɪtɪd/",
  "component": "/kʌmpˈoʊnʌnt/",
  "comprise": "/kʌmprˈaɪz/",
  "conclusion": "/kʌnklˈuʒʌn/",
  "conflict": "/kˈɑnflɪkt/",
  "consequence": "/kˈɑnsʌkwʌns/",
  "constant": "/kˈɑnstʌnt/",
  "consumption": "/kʌnsˈʌmpʃʌn/",
  "conventional": "/kʌnvˈɛnʃʌnʌl/",
  "convince": "/kʌnvˈɪns/",
  "corridor": "/kˈɔrʌdɝ/",
  "cottage": "/kˈɑtʌdʒ/",
  "cream": "/krˈim/",
  "crime": "/krˈaɪm/",
  "crisis": "/krˈaɪsʌs/",
  "critical": "/krˈɪtɪkʌl/",
  "crucial": "/krˈuʃʌl/",
  "cycle": "/sˈaɪkʌl/",
  "daily routine": "/dˈeɪli rutˈin/",
  "ddt": "/dˌidˌˈiti/",
  "deceased": "/dɪsˈist/",
  "deep down": "/dˈip dˈaʊn/",
  "defeat": "/dɪfˈit/",
  "demonstrate": "/dˈɛmʌnstrˌeɪt/",
  "depth": "/dˈɛpθ/",
  "detect": "/dɪtˈɛkt/",
  "device": "/dɪvˈaɪs/",
  "devote": "/dɪvˈoʊt/",
  "devote... to": "/dɪvˈoʊt tˈu/",
  "differ": "/dˈɪfɝ/",
  "digest": "/daɪdʒˈɛst/",
  "display": "/dɪsplˈeɪ/",
  "distant": "/dˈɪstʌnt/",
  "distinct": "/dɪstˈɪŋkt/",
  "distinguish": "/dɪstˈɪŋɡwɪʃ/",
  "distract": "/dɪstrˈækt/",
  "doctorate": "/dˈɑktɝʌt/",
  "domestic": "/dʌmˈɛstɪk/",
  "draft": "/drˈæft/",
  "early on": "/ˈɝli ˈɑn/",
  "edge": "/ˈɛdʒ/",
  "educator": "/ˈɛdʒʌkˌeɪtɝ/",
  "efficient": "/ɪfˈɪʃʌnt/",
  "electrical": "/ɪlˈɛktrɪkʌl/",
  "embarrassed": "/ɪmbˈɛrʌst/",
  "emphasis": "/ˈɛmfʌsʌs/",
  "employ": "/ɛmplˈɔɪ/",
  "encounter": "/ɪnkˈaʊntɝ/",
  "enormous": "/ɪnˈɔrmʌs/",
  "entertainment": "/ˌɛntɝˈteɪnmʌnt/",
  "entirely": "/ɪntˈaɪɝli/",
  "envision": "/ɛnvˈɪʒʌn/",
  "essay": "/ɛsˈeɪ/",
  "essential": "/ɛsˈɛnʃʌl/",
  "estimate": "/ˈɛstʌmʌt/",
  "evaluate": "/ɪvˈæljuˌeɪt/",
  "expand": "/ɪkspˈænd/",
  "extension": "/ɪkstˈɛnʃʌn/",
  "extract": "/ˈɛkstrˌækt/",
  "extraordinary": "/ˌɛkstrˈʌɔrdʌnˌɛri/",
  "fake": "/fˈeɪk/",
  "fantasy": "/fˈæntʌsi/",
  "fashion": "/fˈæʃʌn/",
  "favour (name favor)": "/fˈeɪvɝ/",
  "flee": "/flˈi/",
  "florence nightingale": "/flˈɔrʌns nˈaɪtɪŋɡeɪl/",
  "flow": "/flˈoʊ/",
  "flow chart": "/flˈoʊ tʃˈɑrt/",
  "for instance": "/fˈɔr ˈɪnstʌns/",
  "forecast": "/fˈɔrkˌæst/",
  "formula": "/fˈɔrmjʌlʌ/",
  "found": "/fˈaʊnd/",
  "fountain": "/fˈaʊntʌn/",
  "generate": "/dʒˈɛnɝˌeɪt/",
  "genius": "/dʒˈinjʌs/",
  "gentle": "/dʒˈɛntʌl/",
  "gesture": "/dʒˈɛstʃɝ/",
  "glacier": "/ɡlˈeɪʃɝ/",
  "gradually": "/ɡrˈædʒuʌli/",
  "grain": "/ɡrˈeɪn/",
  "grocery": "/ɡrˈoʊsɝi/",
  "hence": "/hˈɛns/",
  "hitler": "/hˈɪtlɝ/",
  "hybrid": "/hˈaɪbrʌd/",
  "identical": "/aɪdˈɛntɪkʌl/",
  "imply": "/ˌɪmpˈlaɪ/",
  "in other words": "/ɪn ˈʌðɝ wˈɝdz/",
  "in this sense (in ... sense)": "/ɪn ðˈɪs sˈɛns/",
  "in turn": "/ɪn tˈɝn/",
  "incident": "/ˈɪnsʌdʌnt/",
  "incredible": "/ˌɪnkˈrɛdʌbʌl/",
  "infer": "/ˌɪnˈfɝ/",
  "innovation": "/ˌɪnʌˈveɪʃʌn/",
  "inquire (also enquire)": "/ˌɪnkˈwaɪr/",
  "insist": "/ˌɪnˈsɪst/",
  "insist on": "/ˌɪnˈsɪst ˈɑn/",
  "instance": "/ˈɪnstʌns/",
  "instant": "/ˈɪnstʌnt/",
  "institute": "/ˈɪnstʌtˌut/",
  "institution": "/ˌɪnstɪˈtuʃʌn/",
  "integrate": "/ˈɪntʌɡrˌeɪt/",
  "integrated": "/ˈɪntʌɡrˌeɪtʌd/",
  "intense": "/ˌɪnˈtɛns/",
  "interaction": "/ˌɪntˈɝækʃʌn/",
  "internal": "/ˌɪnˈtɝnʌl/",
  "interpret": "/ˌɪnˈtɝprʌt/",
  "intervene": "/ˌɪntɝˈvin/",
  "iron": "/ˈaɪɝn/",
  "isaac newton": "/ˈaɪzʌk nˈutʌn/",
  "jewish": "/dʒˈuɪʃ/",
  "journalist": "/dʒˈɝnʌlʌst/",
  "keep in touch (with ...)": "/kˈip ɪn tˈʌtʃ/",
  "knob": "/nˈɑb/",
  "label": "/lˈeɪbʌl/",
  "leak": "/lˈik/",
  "led": "/lˈɛd/",
  "leisure": "/lˈɛʒɝ/",
  "leopard": "/lˈɛpɝd/",
  "librarian": "/laɪbrˈɛrˌiʌn/",
  "liquid": "/lˈɪkwʌd/",
  "live off": "/lˈaɪv ˈɔf/",
  "lower": "/lˈoʊɝ/",
  "lung": "/lˈʌŋ/",
  "luxury": "/lˈʌɡʒɝi/",
  "make inferences": "/mˈeɪk ˈɪnfɝˌɛnsɪz/",
  "malaria": "/mʌlˈɛriʌ/",
  "melbourne": "/mˈɛlbɝn/",
  "merely": "/mˈɪrli/",
  "mineral": "/mˈɪnɝʌl/",
  "mode": "/mˈoʊd/",
  "mostly": "/mˈoʊstli/",
  "mourn": "/mˈɔrn/",
  "moustache (especially us mustache)": "/mˈʌstˌæʃ/",
  "nevertheless": "/nˌɛvɝðʌˈlɛs/",
  "nobel prize": "/noʊbˈɛl prˈaɪz/",
  "nonverbal": "/nɑnvˈɝbʌl/",
  "novel": "/nˈɑvʌl/",
  "novelist": "/nˈɑvʌlʌst/",
  "numerous": "/nˈumɝʌs/",
  "nutrition": "/nutrˈɪʃʌn/",
  "nutritional": "/nutrˈɪʃʌnʌl/",
  "nutritious": "/nutrˈɪʃʌs/",
  "obey": "/oʊbˈeɪ/",
  "objective": "/ʌbdʒˈɛktɪv/",
  "obtain": "/ʌbtˈeɪn/",
  "occupation": "/ˌɑkjʌˈpeɪʃʌn/",
  "occupy": "/ˈɑkjʌpˌaɪ/",
  "on the move": "/ˈɑn ðʌ mˈuv/",
  "oppose": "/ʌpˈoʊz/",
  "organic": "/ɔrɡˈænɪk/",
  "output": "/ˈaʊtpˌʊt/",
  "overcome": "/ˈoʊvɝkˌʌm/",
  "paragraph": "/pˈærʌɡrˌæf/",
  "passion": "/pˈæʃʌn/",
  "patent": "/pˈætʌnt/",
  "peculiarity": "/pɪkjˌulˈiɛrʌti/",
  "pedal": "/pˈɛdʌl/",
  "penicillin": "/pˌɛnʌˈsɪlʌn/",
  "perceive": "/pɝsˈiv/",
  "persuade": "/pɝswˈeɪd/",
  "pesticide": "/pˈɛstʌsˌaɪd/",
  "photoelectric": "/fˌoʊtoʊɪˈlɛktrɪk/",
  "phrase": "/frˈeɪz/",
  "physiology": "/fˌɪzˈiɑlʌdʒi/",
  "pirate": "/pˈaɪrʌt/",
  "polar": "/pˈoʊlɝ/",
  "politician": "/pˌɑlʌˈtɪʃʌn/",
  "pollinate": "/pˈɑlʌnˌeɪt/",
  "pose": "/pˈoʊz/",
  "potential": "/pʌtˈɛnʃʌl/",
  "potentially": "/pʌtˈɛnʃʌli/",
  "poverty": "/pˈɑvɝti/",
  "predict": "/prɪdˈɪkt/",
  "prediction": "/pridˈɪkʃʌn/",
  "preference": "/prˈɛfɝʌns/",
  "princeton": "/prˈɪnstʌn/",
  "professor": "/prʌfˈɛsɝ/",
  "prohibit": "/proʊhˈɪbʌt/",
  "prohibition": "/prˌoʊʌˈbɪʃʌn/",
  "property": "/prˈɑpɝti/",
  "prospect": "/prˈɑspɛkt/",
  "rare": "/rˈɛr/",
  "react": "/riˈækt/",
  "reality": "/rˌˈiælʌtˌi/",
  "reindeer": "/rˈeɪndˌɪr/",
  "relativity": "/rˌɛlʌˈtɪvʌti/",
  "relevant": "/rˈɛlʌvʌnt/",
  "reliable": "/rɪlˈaɪʌbʌl/",
  "remarkable": "/rɪmˈɑrkʌbʌl/",
  "remote": "/rɪmˈoʊt/",
  "remote control": "/rɪmˈoʊt kʌntrˈoʊl/",
  "resist": "/rɪzˈɪst/",
  "resistance": "/rɪzˈɪstʌns/",
  "reveal": "/rɪvˈil/",
  "rewarding": "/rɪwˈɔrdɪŋ/",
  "roller coaster": "/rˈoʊlɝ kˈoʊstɝ/",
  "root": "/rˈut/",
  "route": "/rˈut/",
  "routine": "/rutˈin/",
  "rural": "/rˈʊrʌl/",
  "salty": "/sˈɔlti/",
  "sami": "/sˈæmi/",
  "sars": "/sˈɑrz/",
  "scientific": "/sˌaɪʌnˈtɪfɪk/",
  "secure": "/sɪkjˈʊr/",
  "security": "/sɪkjˈʊrʌti/",
  "sensor": "/sˈɛnsɝ/",
  "set out": "/sˈɛt ˈaʊt/",
  "shortage": "/ʃˈɔrtʌdʒ/",
  "siberian": "/saɪbˈɪriʌn/",
  "signpost": "/sˈaɪnpˌoʊst/",
  "slight": "/slˈaɪt/",
  "slightly": "/slˈaɪtli/",
  "slump": "/slˈʌmp/",
  "sneeze": "/snˈiz/",
  "soil": "/sˈɔɪl/",
  "sorghum": "/sˈɔrɡʌm/",
  "sour": "/sˈaʊɝ/",
  "splendid": "/splˈɛndɪd/",
  "stare": "/stˈɛr/",
  "steam": "/stˈim/",
  "straighten up": "/strˈeɪtʌn ˈʌp/",
  "strain": "/strˈeɪn/",
  "stretch": "/strˈɛtʃ/",
  "structure": "/strˈʌktʃɝ/",
  "substance": "/sˈʌbstʌns/",
  "sum": "/sˈʌm/",
  "sum up": "/sˈʌm ˈʌp/",
  "superb": "/sʊpˈɝb/",
  "sweden": "/swˈidʌn/",
  "swing": "/swˈɪŋ/",
  "swiss": "/swˈɪs/",
  "switch": "/swˈɪtʃ/",
  "switch off/on": "/swˈɪtʃ ˈɔf ˈɑn/",
  "switzerland": "/swˈɪtsɝlʌnd/",
  "tackle": "/tˈækʌl/",
  "take up a position": "/tˈeɪk ˈʌp ʌ pʌzˈɪʃʌn/",
  "teapot": "/tˈipˌɑt/",
  "tendency": "/tˈɛndʌnsi/",
  "territory": "/tˈɛrɪtˌɔri/",
  "the amish": "/ðʌ ˈɑmɪʃ/",
  "the arctic circle": "/ðʌ ˈɑrktɪk sˈɝkʌl/",
  "theme": "/θˈim/",
  "theme park": "/θˈim pˈɑrk/",
  "theory": "/θˈɪri/",
  "tick": "/tˈɪk/",
  "tone": "/tˈoʊn/",
  "trial": "/trˈaɪʌl/",
  "tunnel": "/tˈʌnʌl/",
  "twin": "/twˈɪn/",
  "ultimately": "/ˈʌltʌmʌtli/",
  "up to": "/ˈʌp tˈu/",
  "upside down": "/ˈʌpsaɪd dˈaʊn/",
  "urban": "/ˈɝbʌn/",
  "valley": "/vˈæli/",
  "vary": "/vˈɛri/",
  "vast": "/vˈæst/",
  "vietnam": "/viˌɛtˈnɑm/",
  "visible": "/vˈɪzʌbʌl/",
  "vision": "/vˈɪʒʌn/",
  "vital": "/vˈaɪtʌl/",
  "waist": "/wˈeɪst/",
  "wander": "/wˈɑndɝ/",
  "warning": "/wˈɔrnɪŋ/",
  "wear and tear": "/wˈɛr ʌnd tˈɛr/",
  "weep": "/wˈip/",
  "wheat": "/wˈit/",
  "widespread": "/wˈaɪdsprɛd/",
  "wire": "/wˈaɪɝ/",
  "wiring": "/wˈaɪrɪŋ/",
  "witness": "/wˈɪtnʌs/",
  "wormwood": "/wˈɝmwˌʊd/",
  "yield": "/jˈild/"
};

